name: "Sphinx"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: build
      run: |
        # python -m pip install --upgrade pip
        cd sphinx
        pip install -r requirements.txt
        sphinx-build source build

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: sphinx/build/

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: sphinx/build
